//! Türkçe (tr-TR) arayüz etiketleri.
//!
//! Zed'de henüz resmi bir çeviri altyapısı (i18n) bulunmadığı için bu tablo,
//! komut paleti, which-key ve tuş haritası düzenleyicisinde görünen aksiyon
//! adlarını (ör. `editor::GoToDefinition`) Türkçe karşılıklarıyla eşler.
//!
//! ÖNEMLİ: Anahtar değerler `action.name()` tarafından üretilen *tam* aksiyon
//! adlarıdır (ör. `workspace::NewFile`). Tuş bağlamaları (keymap.json) bu
//! adları kullandığı için etiketlerin çevrilmesi tuş bağlamalarını bozmaz.
//!
//! Tabloda olmayan aksiyon adları için çağıran taraf İngilizce
//! `humanize_action_name` çıktısına düşer.

/// `action.name()` değerini Türkçe etikete çevirir. Eşleşme yoksa `None` döner.
pub fn tr_tr_label(action_name: &str) -> Option<&'static str> {
    match action_name {
        // ── Zed ──────────────────────────────────────────────────────────
        "zed::About" => Some("zed hakkında"),
        "zed::Quit" => Some("zed'den çık"),
        "zed::OpenSettings" => Some("ayarları aç"),
        "zed::OpenSettingsFile" => Some("ayarlar dosyasını aç"),
        "zed::OpenProjectSettings" => Some("proje ayarlarını aç"),
        "zed::OpenProjectSettingsFile" => Some("proje ayarları dosyasını aç"),
        "zed::OpenDefaultKeymap" => Some("varsayılan tuş bağlamalarını aç"),
        "zed::OpenKeymap" => Some("tuş haritasını aç"),
        "zed::OpenKeymapFile" => Some("tuş haritası dosyasını aç"),
        "zed::OpenDefaultSettings" => Some("varsayılan ayarları aç"),
        "zed::OpenProjectTasks" => Some("tasks.json'ı düzenle"),
        "zed::OpenProjectDebugTasks" => Some("debug.json'ı düzenle"),
        "zed::OpenRecent" => Some("son açılanlar"),
        "zed::OpenRemote" => Some("uzak proje aç"),
        "zed::Extensions" => Some("uzantılar"),
        "zed::OpenTelemetryLog" => Some("telemetri günlüğünü aç"),
        "zed::OpenLicenses" => Some("bağımlılık lisanslarını aç"),
        "zed::OpenDocs" => Some("belgeleri aç"),
        "zed::OpenBrowser" => Some("tarayıcıda aç"),
        "zed::ChangeKeybinding" => Some("tuş bağlamasını değiştir"),
        "zed::theme_selector::Toggle" => Some("tema seç"),
        "zed::icon_theme_selector::Toggle" => Some("simge teması seç"),
        "zed::command_palette::Toggle" => Some("komut paleti"),
        "zed::outline::Toggle" => Some("anahat"),
        "zed::workspace::CopyPath" => Some("yolu kopyala"),
        "zed::workspace::CopyRelativePath" => Some("göreli yolu kopyala"),
        "zed::editor::RevealInFileManager" => Some("dosya yöneticisinde göster"),
        "zed::feedback::FileBugReport" => Some("hata raporu gönder"),
        "zed::feedback::RequestFeature" => Some("özellik iste"),
        "zed::feedback::EmailZed" => Some("zed'e e-posta gönder"),
        "zed::feedback::OpenZedRepo" => Some("zed deposunu aç"),

        // ── Çalışma alanı (workspace) ────────────────────────────────────
        "workspace::NewFile" => Some("yeni dosya"),
        "workspace::NewWindow" => Some("yeni pencere"),
        "workspace::OpenFiles" => Some("dosyaları aç"),
        "workspace::Open" => Some("aç"),
        "workspace::AddFolderToProject" => Some("projeye klasör ekle"),
        "workspace::Save" => Some("kaydet"),
        "workspace::SaveAs" => Some("farklı kaydet"),
        "workspace::SaveAll" => Some("tümünü kaydet"),
        "workspace::CloseActiveItem" => Some("etkin öğeyi kapat"),
        "workspace::CloseProject" => Some("projeyi kapat"),
        "workspace::CloseWindow" => Some("pencereyi kapat"),
        "workspace::CloseAllItemsAndPanes" => Some("tüm öğeleri ve bölmeleri kapat"),
        "workspace::CloseInactiveTabsAndPanes" => Some("etkin olmayan sekmeleri ve bölmeleri kapat"),
        "workspace::CloseActiveDock" => Some("etkin paneli kapat"),
        "workspace::ToggleFileFinder" => Some("dosyaya git"),
        "workspace::DeploySearch" => Some("projede ara"),
        "workspace::ToggleLeftDock" => Some("sol paneli aç/kapat"),
        "workspace::ToggleRightDock" => Some("sağ paneli aç/kapat"),
        "workspace::ToggleBottomDock" => Some("alt paneli aç/kapat"),
        "workspace::ToggleAllDocks" => Some("tüm panelleri aç/kapat"),
        "workspace::SplitUp" => Some("yukarı böl"),
        "workspace::SplitDown" => Some("aşağı böl"),
        "workspace::SplitLeft" => Some("sola böl"),
        "workspace::SplitRight" => Some("sağa böl"),
        "workspace::GoBack" => Some("geri"),
        "workspace::GoForward" => Some("ileri"),
        "workspace::ActivatePane" => Some("bölmeye geç"),
        "workspace::ActivateNextPane" => Some("sonraki bölmeye geç"),
        "workspace::ActivatePreviousPane" => Some("önceki bölmeye geç"),
        "workspace::ActivatePaneUp" => Some("üstteki bölmeye geç"),
        "workspace::ActivatePaneDown" => Some("alttaki bölmeye geç"),
        "workspace::ActivatePaneLeft" => Some("soldaki bölmeye geç"),
        "workspace::ActivatePaneRight" => Some("sağdaki bölmeye geç"),
        "workspace::NewTerminal" => Some("yeni terminal"),

        // ── Bölme (pane) ─────────────────────────────────────────────────
        "pane::ActivateItem" => Some("öğeyi etkinleştir"),
        "pane::ActivateLastItem" => Some("son öğeyi etkinleştir"),
        "pane::ActivateNextItem" => Some("sonraki öğeye geç"),
        "pane::ActivatePreviousItem" => Some("önceki öğeye geç"),
        "pane::AlternateFile" => Some("alternatif dosyaya geç"),
        "pane::CloseActiveItem" => Some("etkin öğeyi kapat"),
        "pane::CloseAllItems" => Some("tüm öğeleri kapat"),
        "pane::CloseCleanItems" => Some("temiz öğeleri kapat"),
        "pane::CloseItemsToTheLeft" => Some("soldaki öğeleri kapat"),
        "pane::CloseItemsToTheRight" => Some("sağdaki öğeleri kapat"),
        "pane::CloseOtherItems" => Some("diğer öğeleri kapat"),
        "pane::GoBack" => Some("geri"),
        "pane::GoForward" => Some("ileri"),
        "pane::GoToOlderTag" => Some("eski etikete git"),
        "pane::ReopenClosedItem" => Some("kapatılan öğeyi yeniden aç"),
        "pane::RevealInProjectPanel" => Some("proje panelinde göster"),
        "pane::SplitDown" => Some("aşağı böl"),
        "pane::SplitHorizontal" => Some("yatay böl"),
        "pane::SplitLeft" => Some("sola böl"),
        "pane::SplitRight" => Some("sağa böl"),
        "pane::SplitUp" => Some("yukarı böl"),
        "pane::SplitVertical" => Some("dikey böl"),
        "pane::SwapItemLeft" => Some("öğeyi sola taşı"),
        "pane::SwapItemRight" => Some("öğeyi sağa taşı"),
        "pane::TogglePinTab" => Some("sekmeyi sabitle/kaldır"),
        "pane::DeploySearch" => Some("projede ara"),

        // ── Editör (editor) ──────────────────────────────────────────────
        "editor::GoToDefinition" => Some("editör: tanıma git"),
        "editor::GoToDeclaration" => Some("editör: bildirime git"),
        "editor::GoToTypeDefinition" => Some("editör: tür tanımına git"),
        "editor::GoToImplementation" => Some("editör: uygulamaya git"),
        "editor::FindAllReferences" => Some("editör: tüm başvuruları bul"),
        "editor::GoToDiagnostic" => Some("editör: sonraki soruna git"),
        "editor::GoToPreviousDiagnostic" => Some("editör: önceki soruna git"),
        "editor::GoToHunk" => Some("editör: sonraki değişiklik bloğuna git"),
        "editor::GoToPreviousHunk" => Some("editör: önceki değişiklik bloğuna git"),
        "editor::GoToNextChange" => Some("editör: sonraki değişikliğe git"),
        "editor::GoToPreviousChange" => Some("editör: önceki değişikliğe git"),
        "editor::Rename" => Some("editör: yeniden adlandır"),
        "editor::Format" => Some("editör: biçimle"),
        "editor::FormatSelections" => Some("editör: seçimleri biçimle"),
        "editor::OrganizeImports" => Some("editör: içe aktarmaları düzenle"),
        "editor::ToggleComments" => Some("editör: yorumları aç/kapat"),
        "editor::ToggleBlockComments" => Some("editör: blok yorumlarını aç/kapat"),
        "editor::ToggleBreakpoint" => Some("editör: kesme noktasını aç/kapat"),
        "editor::EditLogBreakpoint" => Some("editör: kesme noktasını düzenle"),
        "editor::ToggleSoftWrap" => Some("editör: sarmalamayı aç/kapat"),
        "editor::ToggleInlayHints" => Some("editör: satır içi ipuçlarını aç/kapat"),
        "editor::ToggleLineNumbers" => Some("editör: satır numaralarını aç/kapat"),
        "editor::Fold" => Some("editör: katla"),
        "editor::FoldAll" => Some("editör: tümünü katla"),
        "editor::UnfoldAll" => Some("editör: tümünü aç"),
        "editor::ToggleFold" => Some("editör: katlamayı aç/kapat"),
        "editor::ToggleFoldAll" => Some("editör: tüm katlamaları aç/kapat"),
        "editor::FoldRecursive" => Some("editör: yinelemeli katla"),
        "editor::UnfoldRecursive" => Some("editör: yinelemeli aç"),
        "editor::ToggleFoldRecursive" => Some("editör: yinelemeli katlamayı aç/kapat"),
        "editor::FoldSelectedRanges" => Some("editör: seçili aralıkları katla"),
        "editor::UnfoldLines" => Some("editör: satırları aç"),
        "editor::MoveLineUp" => Some("editör: satırı yukarı taşı"),
        "editor::MoveLineDown" => Some("editör: satırı aşağı taşı"),
        "editor::DuplicateLineUp" => Some("editör: satırı yukarı çoğalt"),
        "editor::DuplicateLineDown" => Some("editör: satırı aşağı çoğalt"),
        "editor::SelectLargerSyntaxNode" => Some("editör: seçimi genişlet"),
        "editor::SelectSmallerSyntaxNode" => Some("editör: seçimi daralt"),
        "editor::SelectNextSyntaxNode" => Some("editör: sonraki sözdizimi düğümünü seç"),
        "editor::SelectPreviousSyntaxNode" => Some("editör: önceki sözdizimi düğümünü seç"),
        "editor::SelectNext" => Some("editör: sonraki geçtiği yeri seç"),
        "editor::SelectPrevious" => Some("editör: önceki geçtiği yeri seç"),
        "editor::SelectAllMatches" => Some("editör: tüm geçtiği yerleri seç"),
        "editor::AddSelectionAbove" => Some("editör: üstüne imleç ekle"),
        "editor::AddSelectionBelow" => Some("editör: altına imleç ekle"),
        "editor::ShowCompletions" => Some("editör: tamamlamaları göster"),
        "editor::ShowWordCompletions" => Some("editör: sözcük tamamlamalarını göster"),
        "editor::ShowSignatureHelp" => Some("editör: imza yardımını göster"),
        "editor::ToggleCodeActions" => Some("editör: kod eylemlerini aç/kapat"),
        "editor::Hover" => Some("editör: araç ipucunu göster"),
        "editor::OpenContextMenu" => Some("editör: bağlam menüsünü aç"),
        "editor::RevealInFileManager" => Some("editör: dosya yöneticisinde göster"),
        "editor::Copy" => Some("editör: kopyala"),
        "editor::Cut" => Some("editör: kes"),
        "editor::Paste" => Some("editör: yapıştır"),
        "editor::Undo" => Some("editör: geri al"),
        "editor::Redo" => Some("editör: yinele"),
        "editor::SelectAll" => Some("editör: tümünü seç"),
        "editor::UndoSelection" => Some("editör: seçimi geri al"),
        "editor::RedoSelection" => Some("editör: seçimi yinele"),
        "editor::DeleteLine" => Some("editör: satırı sil"),
        "editor::DeleteToBeginningOfLine" => Some("editör: satır başına kadar sil"),
        "editor::DeleteToNextWordEnd" => Some("editör: sonraki sözcük sonuna kadar sil"),
        "editor::DeleteToPreviousWordStart" => Some("editör: önceki sözcük başına kadar sil"),
        "editor::DeleteToNextSubwordEnd" => Some("editör: sonraki alt sözcük sonuna kadar sil"),
        "editor::DeleteToPreviousSubwordStart" => Some("editör: önceki alt sözcük başına kadar sil"),
        "editor::JoinLines" => Some("editör: satırları birleştir"),
        "editor::Rewrap" => Some("editör: yeniden sar"),
        "editor::MoveToBeginningOfLine" => Some("editör: satır başına git"),
        "editor::MoveToEndOfLine" => Some("editör: satır sonuna git"),
        "editor::MoveToBeginning" => Some("editör: başa git"),
        "editor::MoveToEnd" => Some("editör: sona git"),
        "editor::MoveToEnclosingBracket" => Some("editör: kapsayan paranteze git"),
        "editor::MoveToNextWordEnd" => Some("editör: sonraki sözcük sonuna git"),
        "editor::MoveToPreviousWordStart" => Some("editör: önceki sözcük başına git"),
        "editor::MoveToNextSubwordEnd" => Some("editör: sonraki alt sözcük sonuna git"),
        "editor::MoveToPreviousSubwordStart" => Some("editör: önceki alt sözcük başına git"),
        "editor::MoveToStartOfLargerSyntaxNode" => Some("editör: daha büyük sözdizimi düğümünün başına git"),
        "editor::MoveToEndOfLargerSyntaxNode" => Some("editör: daha büyük sözdizimi düğümünün sonuna git"),
        "editor::MoveUp" => Some("editör: yukarı taşı"),
        "editor::MoveDown" => Some("editör: aşağı taşı"),
        "editor::MoveLeft" => Some("editör: sola taşı"),
        "editor::MoveRight" => Some("editör: sağa taşı"),
        "editor::LineUp" => Some("editör: yukarı satır"),
        "editor::LineDown" => Some("editör: aşağı satır"),
        "editor::PageUp" => Some("editör: yukarı sayfa"),
        "editor::PageDown" => Some("editör: aşağı sayfa"),
        "editor::SelectUp" => Some("editör: yukarıyı seç"),
        "editor::SelectDown" => Some("editör: aşağıyı seç"),
        "editor::SelectLeft" => Some("editör: solu seç"),
        "editor::SelectRight" => Some("editör: sağı seç"),
        "editor::SelectToBeginning" => Some("editör: başa kadar seç"),
        "editor::SelectToEnd" => Some("editör: sona kadar seç"),
        "editor::SelectToBeginningOfLine" => Some("editör: satır başına kadar seç"),
        "editor::SelectToEndOfLine" => Some("editör: satır sonuna kadar seç"),
        "editor::SelectLine" => Some("editör: satırı seç"),
        "editor::SelectEnclosingSymbol" => Some("editör: kapsayan simgeyi seç"),
        "editor::SelectPageUp" => Some("editör: yukarı sayfayı seç"),
        "editor::SelectPageDown" => Some("editör: aşağı sayfayı seç"),
        "editor::SelectToNextWordEnd" => Some("editör: sonraki sözcük sonuna kadar seç"),
        "editor::SelectToPreviousWordStart" => Some("editör: önceki sözcük başına kadar seç"),
        "editor::SelectToNextSubwordEnd" => Some("editör: sonraki alt sözcük sonuna kadar seç"),
        "editor::SelectToPreviousSubwordStart" => Some("editör: önceki alt sözcük başına kadar seç"),
        "editor::SplitSelectionIntoLines" => Some("editör: seçimi satırlara böl"),
        "editor::OpenSelectionsInMultibuffer" => Some("editör: seçimleri çoklu tamponda aç"),
        "editor::OpenSelectedFilename" => Some("editör: seçili dosyayı aç"),
        "editor::OpenUrl" => Some("editör: URL'yi aç"),
        "editor::DisplayCursorNames" => Some("editör: imleç adlarını göster"),
        "editor::ExpandAllDiffHunks" => Some("editör: tüm fark bloklarını genişlet"),
        "editor::ToggleSelectedDiffHunks" => Some("editör: seçili fark bloklarını aç/kapat"),
        "editor::ExpandExcerpts" => Some("editör: alıntıları genişlet"),
        "editor::OpenExcerpts" => Some("editör: alıntıları aç"),
        "editor::OpenExcerptsSplit" => Some("editör: alıntıları bölünmüş aç"),
        "editor::CopyPath" => Some("editör: yolu kopyala"),
        "editor::SaveLocation" => Some("editör: konumu kaydet"),
        "editor::ShowCharacterPalette" => Some("editör: karakter paletini göster"),
        "editor::ScrollCursorTop" => Some("editör: imleci üste kaydır"),
        "editor::ScrollCursorCenter" => Some("editör: imleci ortaya kaydır"),
        "editor::ScrollCursorBottom" => Some("editör: imleci alta kaydır"),

        // ── Dosya bulucu / satır / sembol ────────────────────────────────
        "file_finder::Toggle" => Some("dosyaya git"),
        "go_to_line::Toggle" => Some("satıra git"),
        "outline::Toggle" => Some("anahat"),
        "outline_panel::ToggleFocus" => Some("anahat panelini aç/kapat"),
        "outline_panel::OpenSelectedEntry" => Some("seçili girdiyi aç"),
        "outline_panel::CopyPath" => Some("yolu kopyala"),
        "outline_panel::RevealInFileManager" => Some("dosya yöneticisinde göster"),
        "diagnostics::Deploy" => Some("tanılar"),

        // ── Terminal ─────────────────────────────────────────────────────
        "terminal_panel::Toggle" => Some("terminal panelini aç/kapat"),
        "terminal::Clear" => Some("terminali temizle"),
        "terminal::Copy" => Some("kopyala"),
        "terminal::Paste" => Some("yapıştır"),
        "terminal::PasteText" => Some("metin yapıştır"),
        "terminal::RerunTask" => Some("görevi yeniden çalıştır"),
        "terminal::ScrollLineUp" => Some("satır yukarı kaydır"),
        "terminal::ScrollLineDown" => Some("satır aşağı kaydır"),
        "terminal::ScrollPageUp" => Some("sayfa yukarı kaydır"),
        "terminal::ScrollPageDown" => Some("sayfa aşağı kaydır"),
        "terminal::ScrollToTop" => Some("en üste kaydır"),
        "terminal::ScrollToBottom" => Some("en alta kaydır"),
        "terminal::ToggleViMode" => Some("vi modunu aç/kapat"),
        "terminal::ShowCharacterPalette" => Some("karakter paletini göster"),

        // ── Sekme değiştirici ────────────────────────────────────────────
        "tab_switcher::Toggle" => Some("sekmeler arasında geç"),
        "tab_switcher::ToggleAll" => Some("tüm sekmeleri göster"),
        "tab_switcher::CloseSelectedItem" => Some("seçili öğeyi kapat"),

        // ── Proje paneli ─────────────────────────────────────────────────
        "project_panel::ToggleFocus" => Some("proje panelini aç/kapat"),
        "project_panel::NewFile" => Some("yeni dosya"),
        "project_panel::NewDirectory" => Some("yeni klasör"),
        "project_panel::NewSearchInDirectory" => Some("dizinde yeni arama"),
        "project_panel::Rename" => Some("yeniden adlandır"),
        "project_panel::Delete" => Some("sil"),
        "project_panel::Trash" => Some("çöp kutusuna taşı"),
        "project_panel::Copy" => Some("kopyala"),
        "project_panel::Cut" => Some("kes"),
        "project_panel::Paste" => Some("yapıştır"),
        "project_panel::CopyPath" => Some("yolu kopyala"),
        "project_panel::Open" => Some("aç"),
        "project_panel::OpenPermanent" => Some("kalıcı olarak aç"),
        "project_panel::OpenSplitHorizontal" => Some("yatay bölünmüş aç"),
        "project_panel::OpenSplitVertical" => Some("dikey bölünmüş aç"),
        "project_panel::OpenWithSystem" => Some("sistemle aç"),
        "project_panel::RevealInFileManager" => Some("dosya yöneticisinde göster"),
        "project_panel::ExpandAllEntries" => Some("tüm girdileri genişlet"),
        "project_panel::CollapseAllEntries" => Some("tüm girdileri daralt"),
        "project_panel::ExpandSelectedEntry" => Some("seçili girdiyi genişlet"),
        "project_panel::CollapseSelectedEntry" => Some("seçili girdiyi daralt"),
        "project_panel::SelectParent" => Some("üst dizini seç"),
        "project_panel::SelectNextDirectory" => Some("sonraki dizini seç"),
        "project_panel::SelectPrevDirectory" => Some("önceki dizini seç"),
        "project_panel::SelectNextGitEntry" => Some("sonraki git girdisini seç"),
        "project_panel::SelectPrevGitEntry" => Some("önceki git girdisini seç"),
        "project_panel::SelectNextDiagnostic" => Some("sonraki tanıyı seç"),
        "project_panel::SelectPrevDiagnostic" => Some("önceki tanıyı seç"),
        "project_panel::Undo" => Some("geri al"),
        "project_panel::Redo" => Some("yinele"),
        "project_panel::CompareMarkedFiles" => Some("işaretli dosyaları karşılaştır"),

        // ── Arama ────────────────────────────────────────────────────────
        "buffer_search::Deploy" => Some("bul"),
        "buffer_search::DeployReplace" => Some("bul ve değiştir"),
        "buffer_search::Dismiss" => Some("aramayı kapat"),
        "buffer_search::FocusEditor" => Some("editöre odaklan"),
        "buffer_search::UseSelectionForFind" => Some("seçimi bulmada kullan"),
        "project_search::ToggleFocus" => Some("proje aramasına odaklan"),
        "project_search::ToggleFilters" => Some("filtreleri aç/kapat"),
        "project_search::ToggleAllSearchResults" => Some("tüm arama sonuçlarını aç/kapat"),
        "project_search::SearchInNew" => Some("yeni pencerede ara"),
        "search::FocusSearch" => Some("aramaya odaklan"),
        "search::ReplaceAll" => Some("tümünü değiştir"),
        "search::ReplaceNext" => Some("sonrakini değiştir"),
        "search::SelectAllMatches" => Some("tüm eşleşenleri seç"),
        "search::SelectNextMatch" => Some("sonraki eşleşmeyi seç"),
        "search::SelectPreviousMatch" => Some("önceki eşleşmeyi seç"),
        "search::ToggleCaseSensitive" => Some("büyük/küçük harf duyarlılığını aç/kapat"),
        "search::ToggleRegex" => Some("regex'i aç/kapat"),
        "search::ToggleReplace" => Some("değiştirmeyi aç/kapat"),
        "search::ToggleWholeWord" => Some("tam sözcük eşleşmesini aç/kapat"),
        "search::ToggleSelection" => Some("seçimi ara"),
        "search::ToggleIncludeIgnored" => Some("yok sayılanları dahil et"),
        "text_finder::Toggle" => Some("metin bulucuyu aç/kapat"),

        // ── Git ──────────────────────────────────────────────────────────
        "git::Commit" => Some("git: commit"),
        "git::Amend" => Some("git: commit'i düzelt"),
        "git::Push" => Some("git: push"),
        "git::ForcePush" => Some("git: zorla push"),
        "git::Pull" => Some("git: pull"),
        "git::PullRebase" => Some("git: rebase ile pull"),
        "git::Fetch" => Some("git: fetch"),
        "git::StageAll" => Some("git: tümünü hazırla"),
        "git::UnstageAll" => Some("git: tümünün hazırlığını kaldır"),
        "git::StageFile" => Some("git: dosyayı hazırla"),
        "git::UnstageFile" => Some("git: dosyanın hazırlığını kaldır"),
        "git::StageAndNext" => Some("git: hazırla ve sonrakine geç"),
        "git::UnstageAndNext" => Some("git: hazırlığı kaldır ve sonrakine geç"),
        "git::StageRange" => Some("git: aralığı hazırla"),
        "git::ToggleStaged" => Some("git: hazırlanmış durumu aç/kapat"),
        "git::Restore" => Some("git: geri yükle"),
        "git::RestoreFile" => Some("git: dosyayı geri yükle"),
        "git::RestoreAndNext" => Some("git: geri yükle ve sonrakine geç"),
        "git::RestoreTrackedFiles" => Some("git: izlenen dosyaları geri yükle"),
        "git::Diff" => Some("git: diff"),
        "git::Blame" => Some("git: blame"),
        "git::OpenModifiedFiles" => Some("git: değiştirilen dosyaları aç"),
        "git::GenerateCommitMessage" => Some("git: commit mesajı üret"),
        "git::Cancel" => Some("git: iptal"),
        "git::ExpandCommitEditor" => Some("git: commit düzenleyicisini genişlet"),
        "git::ToggleFillCommitEditor" => Some("git: commit düzenleyicisini doldur"),
        "git::ApplyCurrentStash" => Some("git: geçerli stash'i uygula"),
        "git::PopCurrentStash" => Some("git: geçerli stash'i çıkar"),
        "git::DropCurrentStash" => Some("git: geçerli stash'i at"),
        "git::TrashUntrackedFiles" => Some("git: izlenmeyen dosyaları çöpe at"),
        "git::Worktree" => Some("git: worktree"),
        "git::ReviewDiff" => Some("git: diff'i incele"),
        "git_panel::ToggleFocus" => Some("git panelini aç/kapat"),
        "git_panel::ActivateChangesTab" => Some("değişiklikler sekmesine geç"),
        "git_panel::ActivateHistoryTab" => Some("geçmiş sekmesine geç"),
        "git_panel::FocusChanges" => Some("değişikliklere odaklan"),
        "git_panel::FocusEditor" => Some("editöre odaklan"),
        "git_panel::NextEntry" => Some("sonraki girdi"),
        "git_panel::PreviousEntry" => Some("önceki girdi"),
        "git_picker::ActivateBranchesTab" => Some("dallar sekmesine geç"),
        "git_picker::ActivateStashTab" => Some("stash sekmesine geç"),
        "branch_picker::DeleteBranch" => Some("dalı sil"),
        "branch_picker::ForceDeleteBranch" => Some("dalı zorla sil"),
        "branch_picker::CycleBranchFilter" => Some("dal filtresini değiştir"),
        "branch_picker::ToggleFilterMenu" => Some("filtre menüsünü aç/kapat"),
        "branches::OpenRecent" => Some("son dalları aç"),

        // ── Hata ayıklama ────────────────────────────────────────────────
        "debug_panel::ToggleFocus" => Some("hata ayıklayıcı panelini aç/kapat"),
        "debugger::Start" => Some("hata ayıklamayı başlat"),
        "debugger_ui::Start" => Some("hata ayıklamayı başlat"),
        "debugger::Continue" => Some("devam et"),
        "debugger_ui::Continue" => Some("devam et"),
        "debugger::StepOver" => Some("üzerinden adım at"),
        "debugger_ui::StepOver" => Some("üzerinden adım at"),
        "debugger::StepInto" => Some("içine adım at"),
        "debugger_ui::StepInto" => Some("içine adım at"),
        "debugger::StepOut" => Some("dışına adım at"),
        "debugger_ui::StepOut" => Some("dışına adım at"),
        "debugger::Stop" => Some("durdur"),
        "debugger::Pause" => Some("duraklat"),
        "debugger::Rerun" => Some("yeniden çalıştır"),
        "debugger::RerunSession" => Some("oturumu yeniden çalıştır"),
        "debugger::Restart" => Some("yeniden başlat"),
        "debugger::ToggleEnableBreakpoint" => Some("kesme noktasını etkinleştir/devre dışı bırak"),
        "debugger::ToggleSessionPicker" => Some("oturum seçiciyi aç/kapat"),
        "debugger::ToggleThreadPicker" => Some("iş parçacığı seçiciyi aç/kapat"),
        "debugger::UnsetBreakpoint" => Some("kesme noktasını kaldır"),
        "debugger_ui::ClearAllBreakpoints" => Some("tüm kesme noktalarını temizle"),

        // ── Görevler / REPL ──────────────────────────────────────────────
        "task::Spawn" => Some("görev başlat"),
        "task::Rerun" => Some("görevi yeniden çalıştır"),
        "repl::Run" => Some("çalıştır"),
        "repl::RunInPlace" => Some("yerinde çalıştır"),

        // ── Seçiciler ────────────────────────────────────────────────────
        "language_selector::Toggle" => Some("dil seç"),
        "theme_selector::Toggle" => Some("tema seç"),
        "theme::ToggleMode" => Some("tema modunu değiştir"),
        "encoding_selector::Toggle" => Some("kodlama seç"),
        "toolchain::AddToolchain" => Some("araç zinciri ekle"),
        "settings_profile_selector::Toggle" => Some("ayar profili seç"),

        // ── Ayarlar düzenleyici ──────────────────────────────────────────
        "settings_editor::FocusNextFile" => Some("sonraki dosyaya git"),
        "settings_editor::FocusPreviousFile" => Some("önceki dosyaya git"),
        "settings_editor::OpenCurrentFile" => Some("geçerli dosyayı aç"),
        "settings_editor::Minimize" => Some("küçült"),

        // ── İşaretleme (markdown) / görüntü ──────────────────────────────
        "markdown::OpenPreview" => Some("önizlemeyi aç"),
        "markdown::OpenPreviewToTheSide" => Some("yan tarafta önizleme aç"),
        "markdown::Copy" => Some("kopyala"),
        "markdown::CopyAsMarkdown" => Some("markdown olarak kopyala"),
        "markdown::CloseAndReturnToEditor" => Some("kapat ve editöre dön"),
        "markdown::ScrollUp" => Some("yukarı kaydır"),
        "markdown::ScrollDown" => Some("aşağı kaydır"),
        "markdown::ScrollPageUp" => Some("sayfa yukarı kaydır"),
        "markdown::ScrollPageDown" => Some("sayfa aşağı kaydır"),
        "markdown::ScrollToTop" => Some("en üste kaydır"),
        "markdown::ScrollToBottom" => Some("en alta kaydır"),
        "svg::OpenPreview" => Some("önizlemeyi aç"),
        "svg::OpenPreviewToTheSide" => Some("yan tarafta önizleme aç"),
        "image_viewer::ZoomIn" => Some("yakınlaştır"),
        "image_viewer::ZoomOut" => Some("uzaklaştır"),
        "image_viewer::ResetZoom" => Some("yakınlaştırmayı sıfırla"),
        "image_viewer::FitToView" => Some("görünüme sığdır"),
        "image_viewer::ZoomToActualSize" => Some("gerçek boyuta getir"),

        // ── Son projeler / çoklu çalışma alanı ───────────────────────────
        "projects::OpenRecent" => Some("son projeleri aç"),
        "projects::OpenRemote" => Some("uzak proje aç"),
        "recent_projects::AddToWorkspace" => Some("çalışma alanına ekle"),
        "recent_projects::RemoveSelected" => Some("seçileni kaldır"),
        "recent_projects::ToggleActionsMenu" => Some("eylem menüsünü aç/kapat"),
        "multi_workspace::NextProject" => Some("sonraki proje"),
        "multi_workspace::PreviousProject" => Some("önceki proje"),
        "multi_workspace::ToggleWorkspaceSidebar" => Some("çalışma alanı kenar çubuğunu aç/kapat"),
        "multi_workspace::FocusWorkspaceSidebar" => Some("kenar çubuğuna odaklan"),

        // ── İş birliği ───────────────────────────────────────────────────
        "collab_panel::ToggleFocus" => Some("iş birliği panelini aç/kapat"),

        // ── Ajan (yapay zekâ) ────────────────────────────────────────────
        "agent::ToggleFocus" => Some("ajan panelini aç/kapat"),
        "agent::NewThread" => Some("yeni sohbet"),
        "agent::Chat" => Some("sohbet başlat"),
        "agent::ChatWithFollow" => Some("takiple sohbet başlat"),
        "agent::AllowOnce" => Some("bir kez izin ver"),
        "agent::AllowAlways" => Some("her zaman izin ver"),
        "agent::Reject" => Some("reddet"),
        "agent::RejectAll" => Some("tümünü reddet"),
        "agent::RejectOnce" => Some("bir kez reddet"),
        "agent::Keep" => Some("koru"),
        "agent::KeepAll" => Some("tümünü koru"),
        "agent::ManageProfiles" => Some("profilleri yönet"),
        "agent::ManageSkills" => Some("becerileri yönet"),
        "agent::ToggleModelSelector" => Some("model seçiciyi aç/kapat"),
        "agent::ToggleProfileSelector" => Some("profil seçiciyi aç/kapat"),
        "agent::ToggleSearch" => Some("arama yap"),
        "agent::RenameSelectedThread" => Some("seçili sohbeti yeniden adlandır"),
        "agent::ArchiveSelectedThread" => Some("seçili sohbeti arşivle"),
        "agent::RemoveSelectedThread" => Some("seçili sohbeti sil"),
        "agent::ToggleOptionsMenu" => Some("seçenekler menüsünü aç/kapat"),
        "agent::ToggleThinkingMode" => Some("düşünme modunu aç/kapat"),
        "agent::ToggleFastMode" => Some("hızlı modu aç/kapat"),
        "agent::ToggleThinkingEffortMenu" => Some("düşünme çabası menüsünü aç/kapat"),
        "agent::PasteRaw" => Some("ham yapıştır"),
        "agent::SendImmediately" => Some("hemen gönder"),
        "agent::OpenAgentDiff" => Some("ajan farkını aç"),
        "agent::OpenPermissionDropdown" => Some("izin menüsünü aç"),
        "agent::CycleModeSelector" => Some("mod seçiciyi değiştir"),
        "agent::CycleThinkingEffort" => Some("düşünme çabasını değiştir"),
        "agent::CycleFavoriteModels" => Some("favori modelleri değiştir"),
        "agent::UndoLastReject" => Some("son reddi geri al"),
        "agent::ToggleNewThreadMenu" => Some("yeni sohbet menüsünü aç/kapat"),
        "assistant::ToggleFocus" => Some("ajan panelini aç/kapat"),
        "assistant::InlineAssist" => Some("satır içi asistan"),

        // ── Karşılama / kayıt ────────────────────────────────────────────
        "onboarding::ShowWelcome" => Some("karşılama ekranını göster"),
        "onboarding::Finish" => Some("tamamla"),
        "onboarding::SignIn" => Some("giriş yap"),
        "onboarding::OpenAccount" => Some("hesabı aç"),
        "welcome::OpenRecentProject" => Some("son projeyi aç"),

        _ => None,
    }
}
